### ISSUE TITLE
namespace could not be found

### ISSUE THREAD

**Issue by xOnlyFadi** [MsRandom/AmongUsModLoader#1]
Im the only one who is getting this error or other people have it?
![image](https://user-images.githubusercontent.com/63213308/98868969-37e85280-242e-11eb-8be4-fd086421d510.png)

**Comment by MsRandom** [comment]
The current setup process is a bit convoluted, we are working on improving it.

For those classes to be found, you'd need to install BepInEx in your game and then run the game once, then setup the AMONG_US_PATH environment variable in your machine(which is the **relative** path to the game from your project folder).
After that, you should have no compilation errors, granted you are on 2020.10.22s.

To get BepInEx, download the UnityIL2CPP_x86 zip of the latest artifact from https://builds.bepis.io/projects/bepinex_be, then extract it to your game folder to install it, if you're on Linux you also need to manually add the DLL override for winhttp in your winecfg for the wineprefix.

**Comment by xOnlyFadi** [comment]
how do i setup among_us_path i'm confused how to do it

**Comment by MsRandom** [comment]
This should tell you how to set environment variables: https://www.computerhope.com/issues/ch000549.htm

The value of it is the relative path to the game from your project folder, for example, if the project is in `C:\Projects\AmongUsModLoader\AmongUs.Client.Loader`, and your game is in `C:\Games\Among_Us`, then the relative path would be `..\..\..\Games\Among_Us`

**Comment by MsRandom** [comment]
Oh, also. If the latest artifact doesn't work, you can build the specific commit we're using for testing: https://github.com/BepInEx/BepInEx/tree/5bababd7a3158f63f94c57d3fb712f05c2d621bd

**Comment by xOnlyFadi** [comment]
i did the set environment variables and the packages still unavailable in visual studio 2019

**Comment by MsRandom** [comment]
Do you have a BepInEx/unhollowed folder in your game?

**Comment by xOnlyFadi** [comment]
i fixed it it working now

**Comment by xOnlyFadi** [comment]
i have question how do i get among us patches like 
**HarmonyPatch(typeof(PingTracker)** how do i get them?

**Comment by MsRandom** [comment]
What do you mean?

**Comment by xOnlyFadi** [comment]
like when i wanna do an custom text in among us beside the ping section it says ping tracker is not available and i don't how to get those


`[HarmonyPatch(typeof(PingTracker), "Update")]
        public static class HelloFrickOffPatch
        {
            public static void Postfix(PingTracker __instance)
            {
                TextRenderer text = __instance.text;
                text.Text += "[FF1919FF]\n> xOnlyFadi <";
            }
        }`

**Comment by gkazan** [comment]
This is a mod loader and a wrapper so you wouldn't do something like that. Take a look here and see how I used the API of the modloader to create my mod [here](https://github.com/0SoggyMustache0/StopCountdownMod/blob/main/PauseCountdownMod/StopCountdownMod.cs). If you wanted to do something with the ping text you would have to submit a pull request into the modloader adding a wrapper for a way to do that, it's how we make sure mods can work after among us code changes.

**Comment by xOnlyFadi** [comment]
oh ok thanks

**Comment by MsRandom** [comment]
Closing this now.
